/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export declare namespace Brevis {
  export type ProofDataStruct = {
    commitHash: BytesLike;
    vkHash: BytesLike;
    appCommitHash: BytesLike;
    appVkHash: BytesLike;
    smtRoot: BytesLike;
  };

  export type ProofDataStructOutput = [
    string,
    string,
    string,
    string,
    string
  ] & {
    commitHash: string;
    vkHash: string;
    appCommitHash: string;
    appVkHash: string;
    smtRoot: string;
  };

  export type LogExtraInfoStruct = {
    valueFromTopic: BigNumberish;
    valueIndex: BigNumberish;
    contractAddress: string;
    logTopic0: BytesLike;
  };

  export type LogExtraInfoStructOutput = [number, BigNumber, string, string] & {
    valueFromTopic: number;
    valueIndex: BigNumber;
    contractAddress: string;
    logTopic0: string;
  };

  export type LogInfoStruct = {
    logExtraInfo: Brevis.LogExtraInfoStruct;
    logIndex: BigNumberish;
    value: BytesLike;
  };

  export type LogInfoStructOutput = [
    Brevis.LogExtraInfoStructOutput,
    BigNumber,
    string
  ] & {
    logExtraInfo: Brevis.LogExtraInfoStructOutput;
    logIndex: BigNumber;
    value: string;
  };

  export type ReceiptInfoStruct = {
    blkNum: BigNumberish;
    receiptIndex: BigNumberish;
    logs: [
      Brevis.LogInfoStruct,
      Brevis.LogInfoStruct,
      Brevis.LogInfoStruct,
      Brevis.LogInfoStruct,
      Brevis.LogInfoStruct
    ];
  };

  export type ReceiptInfoStructOutput = [
    BigNumber,
    BigNumber,
    [
      Brevis.LogInfoStructOutput,
      Brevis.LogInfoStructOutput,
      Brevis.LogInfoStructOutput,
      Brevis.LogInfoStructOutput,
      Brevis.LogInfoStructOutput
    ]
  ] & {
    blkNum: BigNumber;
    receiptIndex: BigNumber;
    logs: [
      Brevis.LogInfoStructOutput,
      Brevis.LogInfoStructOutput,
      Brevis.LogInfoStructOutput,
      Brevis.LogInfoStructOutput,
      Brevis.LogInfoStructOutput
    ];
  };

  export type StorageInfoStruct = {
    blockHash: BytesLike;
    account: string;
    slot: BytesLike;
    slotValue: BytesLike;
    blockNumber: BigNumberish;
  };

  export type StorageInfoStructOutput = [
    string,
    string,
    string,
    string,
    BigNumber
  ] & {
    blockHash: string;
    account: string;
    slot: string;
    slotValue: string;
    blockNumber: BigNumber;
  };

  export type TransactionInfoStruct = {
    leafHash: BytesLike;
    blockHash: BytesLike;
    blockNumber: BigNumberish;
    blockTime: BigNumberish;
    leafRlpPrefix: BytesLike;
  };

  export type TransactionInfoStructOutput = [
    string,
    string,
    BigNumber,
    BigNumber,
    string
  ] & {
    leafHash: string;
    blockHash: string;
    blockNumber: BigNumber;
    blockTime: BigNumber;
    leafRlpPrefix: string;
  };

  export type ExtractInfosStruct = {
    smtRoot: BytesLike;
    receipts: Brevis.ReceiptInfoStruct[];
    stores: Brevis.StorageInfoStruct[];
    txs: Brevis.TransactionInfoStruct[];
  };

  export type ExtractInfosStructOutput = [
    string,
    Brevis.ReceiptInfoStructOutput[],
    Brevis.StorageInfoStructOutput[],
    Brevis.TransactionInfoStructOutput[]
  ] & {
    smtRoot: string;
    receipts: Brevis.ReceiptInfoStructOutput[];
    stores: Brevis.StorageInfoStructOutput[];
    txs: Brevis.TransactionInfoStructOutput[];
  };
}

export interface BrevisAppInterface extends utils.Interface {
  contractName: "BrevisApp";
  functions: {
    "brevisBatchCallback(uint64,(bytes32,bytes32,bytes32,bytes32,bytes32)[],bytes[])": FunctionFragment;
    "brevisCallback(bytes32,bytes)": FunctionFragment;
    "brevisProof()": FunctionFragment;
    "singleRun(uint64,(bytes32,bytes32,bytes32,bytes32,bytes32),bytes32,bytes32[],uint8,bytes)": FunctionFragment;
    "validateRequest(bytes32,uint64,(bytes32,(uint64,uint64,tuple[5])[],(bytes32,address,bytes32,bytes32,uint64)[],(bytes32,bytes32,uint64,uint64,bytes)[]))": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "brevisBatchCallback",
    values: [BigNumberish, Brevis.ProofDataStruct[], BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "brevisCallback",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "brevisProof",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "singleRun",
    values: [
      BigNumberish,
      Brevis.ProofDataStruct,
      BytesLike,
      BytesLike[],
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "validateRequest",
    values: [BytesLike, BigNumberish, Brevis.ExtractInfosStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "brevisBatchCallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "brevisCallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "brevisProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "singleRun", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "validateRequest",
    data: BytesLike
  ): Result;

  events: {};
}

export interface BrevisApp extends BaseContract {
  contractName: "BrevisApp";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: BrevisAppInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    brevisBatchCallback(
      _chainId: BigNumberish,
      _proofDataArray: Brevis.ProofDataStruct[],
      _appCircuitOutputs: BytesLike[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    brevisCallback(
      _requestId: BytesLike,
      _appCircuitOutput: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    brevisProof(overrides?: CallOverrides): Promise<[string]>;

    singleRun(
      _chainId: BigNumberish,
      _proofData: Brevis.ProofDataStruct,
      _merkleRoot: BytesLike,
      _merkleProof: BytesLike[],
      _nodeIndex: BigNumberish,
      _appCircuitOutput: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    validateRequest(
      _requestId: BytesLike,
      _chainId: BigNumberish,
      _extractInfos: Brevis.ExtractInfosStruct,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  brevisBatchCallback(
    _chainId: BigNumberish,
    _proofDataArray: Brevis.ProofDataStruct[],
    _appCircuitOutputs: BytesLike[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  brevisCallback(
    _requestId: BytesLike,
    _appCircuitOutput: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  brevisProof(overrides?: CallOverrides): Promise<string>;

  singleRun(
    _chainId: BigNumberish,
    _proofData: Brevis.ProofDataStruct,
    _merkleRoot: BytesLike,
    _merkleProof: BytesLike[],
    _nodeIndex: BigNumberish,
    _appCircuitOutput: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  validateRequest(
    _requestId: BytesLike,
    _chainId: BigNumberish,
    _extractInfos: Brevis.ExtractInfosStruct,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    brevisBatchCallback(
      _chainId: BigNumberish,
      _proofDataArray: Brevis.ProofDataStruct[],
      _appCircuitOutputs: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;

    brevisCallback(
      _requestId: BytesLike,
      _appCircuitOutput: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    brevisProof(overrides?: CallOverrides): Promise<string>;

    singleRun(
      _chainId: BigNumberish,
      _proofData: Brevis.ProofDataStruct,
      _merkleRoot: BytesLike,
      _merkleProof: BytesLike[],
      _nodeIndex: BigNumberish,
      _appCircuitOutput: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    validateRequest(
      _requestId: BytesLike,
      _chainId: BigNumberish,
      _extractInfos: Brevis.ExtractInfosStruct,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    brevisBatchCallback(
      _chainId: BigNumberish,
      _proofDataArray: Brevis.ProofDataStruct[],
      _appCircuitOutputs: BytesLike[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    brevisCallback(
      _requestId: BytesLike,
      _appCircuitOutput: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    brevisProof(overrides?: CallOverrides): Promise<BigNumber>;

    singleRun(
      _chainId: BigNumberish,
      _proofData: Brevis.ProofDataStruct,
      _merkleRoot: BytesLike,
      _merkleProof: BytesLike[],
      _nodeIndex: BigNumberish,
      _appCircuitOutput: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    validateRequest(
      _requestId: BytesLike,
      _chainId: BigNumberish,
      _extractInfos: Brevis.ExtractInfosStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    brevisBatchCallback(
      _chainId: BigNumberish,
      _proofDataArray: Brevis.ProofDataStruct[],
      _appCircuitOutputs: BytesLike[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    brevisCallback(
      _requestId: BytesLike,
      _appCircuitOutput: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    brevisProof(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    singleRun(
      _chainId: BigNumberish,
      _proofData: Brevis.ProofDataStruct,
      _merkleRoot: BytesLike,
      _merkleProof: BytesLike[],
      _nodeIndex: BigNumberish,
      _appCircuitOutput: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    validateRequest(
      _requestId: BytesLike,
      _chainId: BigNumberish,
      _extractInfos: Brevis.ExtractInfosStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
