/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export declare namespace Brevis {
  export type ProofDataStruct = {
    commitHash: BytesLike;
    vkHash: BytesLike;
    appCommitHash: BytesLike;
    appVkHash: BytesLike;
    smtRoot: BytesLike;
  };

  export type ProofDataStructOutput = [
    string,
    string,
    string,
    string,
    string
  ] & {
    commitHash: string;
    vkHash: string;
    appCommitHash: string;
    appVkHash: string;
    smtRoot: string;
  };

  export type LogExtraInfoStruct = {
    valueFromTopic: BigNumberish;
    valueIndex: BigNumberish;
    contractAddress: string;
    logTopic0: BytesLike;
  };

  export type LogExtraInfoStructOutput = [number, BigNumber, string, string] & {
    valueFromTopic: number;
    valueIndex: BigNumber;
    contractAddress: string;
    logTopic0: string;
  };

  export type LogInfoStruct = {
    logExtraInfo: Brevis.LogExtraInfoStruct;
    logIndex: BigNumberish;
    value: BytesLike;
  };

  export type LogInfoStructOutput = [
    Brevis.LogExtraInfoStructOutput,
    BigNumber,
    string
  ] & {
    logExtraInfo: Brevis.LogExtraInfoStructOutput;
    logIndex: BigNumber;
    value: string;
  };

  export type ReceiptInfoStruct = {
    blkNum: BigNumberish;
    receiptIndex: BigNumberish;
    logs: [
      Brevis.LogInfoStruct,
      Brevis.LogInfoStruct,
      Brevis.LogInfoStruct,
      Brevis.LogInfoStruct,
      Brevis.LogInfoStruct
    ];
  };

  export type ReceiptInfoStructOutput = [
    BigNumber,
    BigNumber,
    [
      Brevis.LogInfoStructOutput,
      Brevis.LogInfoStructOutput,
      Brevis.LogInfoStructOutput,
      Brevis.LogInfoStructOutput,
      Brevis.LogInfoStructOutput
    ]
  ] & {
    blkNum: BigNumber;
    receiptIndex: BigNumber;
    logs: [
      Brevis.LogInfoStructOutput,
      Brevis.LogInfoStructOutput,
      Brevis.LogInfoStructOutput,
      Brevis.LogInfoStructOutput,
      Brevis.LogInfoStructOutput
    ];
  };

  export type StorageInfoStruct = {
    blockHash: BytesLike;
    account: string;
    slot: BytesLike;
    slotValue: BytesLike;
    blockNumber: BigNumberish;
  };

  export type StorageInfoStructOutput = [
    string,
    string,
    string,
    string,
    BigNumber
  ] & {
    blockHash: string;
    account: string;
    slot: string;
    slotValue: string;
    blockNumber: BigNumber;
  };

  export type TransactionInfoStruct = {
    leafHash: BytesLike;
    blockHash: BytesLike;
    blockNumber: BigNumberish;
    blockTime: BigNumberish;
    leafRlpPrefix: BytesLike;
  };

  export type TransactionInfoStructOutput = [
    string,
    string,
    BigNumber,
    BigNumber,
    string
  ] & {
    leafHash: string;
    blockHash: string;
    blockNumber: BigNumber;
    blockTime: BigNumber;
    leafRlpPrefix: string;
  };

  export type ExtractInfosStruct = {
    smtRoot: BytesLike;
    receipts: Brevis.ReceiptInfoStruct[];
    stores: Brevis.StorageInfoStruct[];
    txs: Brevis.TransactionInfoStruct[];
  };

  export type ExtractInfosStructOutput = [
    string,
    Brevis.ReceiptInfoStructOutput[],
    Brevis.StorageInfoStructOutput[],
    Brevis.TransactionInfoStructOutput[]
  ] & {
    smtRoot: string;
    receipts: Brevis.ReceiptInfoStructOutput[];
    stores: Brevis.StorageInfoStructOutput[];
    txs: Brevis.TransactionInfoStructOutput[];
  };
}

export interface FeeReimbursementAppInterface extends utils.Interface {
  contractName: "FeeReimbursementApp";
  functions: {
    "accountIdAccumulatedFee(uint128)": FunctionFragment;
    "accountIdClaimPeriod(uint128)": FunctionFragment;
    "brevisBatchCallback(uint64,(bytes32,bytes32,bytes32,bytes32,bytes32)[],bytes[])": FunctionFragment;
    "brevisCallback(bytes32,bytes)": FunctionFragment;
    "brevisProof()": FunctionFragment;
    "claim(uint128)": FunctionFragment;
    "claimer()": FunctionFragment;
    "feeRebateTierModule()": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "rewardToken()": FunctionFragment;
    "rewardTokenDecimals()": FunctionFragment;
    "setClaimer(address)": FunctionFragment;
    "setFeeRebateTierModule(address)": FunctionFragment;
    "setRewardToken(address,uint24)": FunctionFragment;
    "setVkHashes(bytes32[],uint16[])": FunctionFragment;
    "singleRun(uint64,(bytes32,bytes32,bytes32,bytes32,bytes32),bytes32,bytes32[],uint8,bytes)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "validateRequest(bytes32,uint64,(bytes32,(uint64,uint64,tuple[5])[],(bytes32,address,bytes32,bytes32,uint64)[],(bytes32,bytes32,uint64,uint64,bytes)[]))": FunctionFragment;
    "vkHashesToCircuitSize(bytes32)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "accountIdAccumulatedFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "accountIdClaimPeriod",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "brevisBatchCallback",
    values: [BigNumberish, Brevis.ProofDataStruct[], BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "brevisCallback",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "brevisProof",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "claim", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "claimer", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "feeRebateTierModule",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rewardToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rewardTokenDecimals",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "setClaimer", values: [string]): string;
  encodeFunctionData(
    functionFragment: "setFeeRebateTierModule",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setRewardToken",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setVkHashes",
    values: [BytesLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "singleRun",
    values: [
      BigNumberish,
      Brevis.ProofDataStruct,
      BytesLike,
      BytesLike[],
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "validateRequest",
    values: [BytesLike, BigNumberish, Brevis.ExtractInfosStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "vkHashesToCircuitSize",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "accountIdAccumulatedFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "accountIdClaimPeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "brevisBatchCallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "brevisCallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "brevisProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claimer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "feeRebateTierModule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rewardToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rewardTokenDecimals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setClaimer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setFeeRebateTierModule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRewardToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setVkHashes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "singleRun", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "vkHashesToCircuitSize",
    data: BytesLike
  ): Result;

  events: {
    "FeeRebateAccumulated(uint128,uint248,uint248,uint248,uint64,uint64)": EventFragment;
    "FeeReimbursed(uint128,uint248)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "VkHashesUpdated(bytes32[],uint16[])": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "FeeRebateAccumulated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "FeeReimbursed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "VkHashesUpdated"): EventFragment;
}

export type FeeRebateAccumulatedEvent = TypedEvent<
  [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber],
  {
    accountId: BigNumber;
    feeRebate: BigNumber;
    volume30D: BigNumber;
    feeRebateWithRate: BigNumber;
    startBlockNumber: BigNumber;
    endBlockNumber: BigNumber;
  }
>;

export type FeeRebateAccumulatedEventFilter =
  TypedEventFilter<FeeRebateAccumulatedEvent>;

export type FeeReimbursedEvent = TypedEvent<
  [BigNumber, BigNumber],
  { accountId: BigNumber; feeRebate: BigNumber }
>;

export type FeeReimbursedEventFilter = TypedEventFilter<FeeReimbursedEvent>;

export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  { previousOwner: string; newOwner: string }
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export type VkHashesUpdatedEvent = TypedEvent<
  [string[], number[]],
  { vkHashes: string[]; sizes: number[] }
>;

export type VkHashesUpdatedEventFilter = TypedEventFilter<VkHashesUpdatedEvent>;

export interface FeeReimbursementApp extends BaseContract {
  contractName: "FeeReimbursementApp";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: FeeReimbursementAppInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    accountIdAccumulatedFee(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    accountIdClaimPeriod(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        startBlockNumber: BigNumber;
        endBlockNumber: BigNumber;
      }
    >;

    brevisBatchCallback(
      _chainId: BigNumberish,
      _proofDataArray: Brevis.ProofDataStruct[],
      _appCircuitOutputs: BytesLike[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    brevisCallback(
      _requestId: BytesLike,
      _appCircuitOutput: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    brevisProof(overrides?: CallOverrides): Promise<[string]>;

    claim(
      accountId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    claimer(overrides?: CallOverrides): Promise<[string]>;

    feeRebateTierModule(overrides?: CallOverrides): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    rewardToken(overrides?: CallOverrides): Promise<[string]>;

    rewardTokenDecimals(overrides?: CallOverrides): Promise<[number]>;

    setClaimer(
      _claimer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setFeeRebateTierModule(
      _feeRebateTierModule: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setRewardToken(
      _rewardToken: string,
      _decimals: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setVkHashes(
      _vkHashes: BytesLike[],
      _sizes: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    singleRun(
      _chainId: BigNumberish,
      _proofData: Brevis.ProofDataStruct,
      _merkleRoot: BytesLike,
      _merkleProof: BytesLike[],
      _nodeIndex: BigNumberish,
      _appCircuitOutput: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    validateRequest(
      _requestId: BytesLike,
      _chainId: BigNumberish,
      _extractInfos: Brevis.ExtractInfosStruct,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    vkHashesToCircuitSize(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<[number]>;
  };

  accountIdAccumulatedFee(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  accountIdClaimPeriod(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & {
      startBlockNumber: BigNumber;
      endBlockNumber: BigNumber;
    }
  >;

  brevisBatchCallback(
    _chainId: BigNumberish,
    _proofDataArray: Brevis.ProofDataStruct[],
    _appCircuitOutputs: BytesLike[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  brevisCallback(
    _requestId: BytesLike,
    _appCircuitOutput: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  brevisProof(overrides?: CallOverrides): Promise<string>;

  claim(
    accountId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  claimer(overrides?: CallOverrides): Promise<string>;

  feeRebateTierModule(overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  rewardToken(overrides?: CallOverrides): Promise<string>;

  rewardTokenDecimals(overrides?: CallOverrides): Promise<number>;

  setClaimer(
    _claimer: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setFeeRebateTierModule(
    _feeRebateTierModule: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setRewardToken(
    _rewardToken: string,
    _decimals: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setVkHashes(
    _vkHashes: BytesLike[],
    _sizes: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  singleRun(
    _chainId: BigNumberish,
    _proofData: Brevis.ProofDataStruct,
    _merkleRoot: BytesLike,
    _merkleProof: BytesLike[],
    _nodeIndex: BigNumberish,
    _appCircuitOutput: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  validateRequest(
    _requestId: BytesLike,
    _chainId: BigNumberish,
    _extractInfos: Brevis.ExtractInfosStruct,
    overrides?: CallOverrides
  ): Promise<boolean>;

  vkHashesToCircuitSize(
    arg0: BytesLike,
    overrides?: CallOverrides
  ): Promise<number>;

  callStatic: {
    accountIdAccumulatedFee(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    accountIdClaimPeriod(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        startBlockNumber: BigNumber;
        endBlockNumber: BigNumber;
      }
    >;

    brevisBatchCallback(
      _chainId: BigNumberish,
      _proofDataArray: Brevis.ProofDataStruct[],
      _appCircuitOutputs: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;

    brevisCallback(
      _requestId: BytesLike,
      _appCircuitOutput: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    brevisProof(overrides?: CallOverrides): Promise<string>;

    claim(accountId: BigNumberish, overrides?: CallOverrides): Promise<void>;

    claimer(overrides?: CallOverrides): Promise<string>;

    feeRebateTierModule(overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    rewardToken(overrides?: CallOverrides): Promise<string>;

    rewardTokenDecimals(overrides?: CallOverrides): Promise<number>;

    setClaimer(_claimer: string, overrides?: CallOverrides): Promise<void>;

    setFeeRebateTierModule(
      _feeRebateTierModule: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setRewardToken(
      _rewardToken: string,
      _decimals: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setVkHashes(
      _vkHashes: BytesLike[],
      _sizes: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    singleRun(
      _chainId: BigNumberish,
      _proofData: Brevis.ProofDataStruct,
      _merkleRoot: BytesLike,
      _merkleProof: BytesLike[],
      _nodeIndex: BigNumberish,
      _appCircuitOutput: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    validateRequest(
      _requestId: BytesLike,
      _chainId: BigNumberish,
      _extractInfos: Brevis.ExtractInfosStruct,
      overrides?: CallOverrides
    ): Promise<boolean>;

    vkHashesToCircuitSize(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<number>;
  };

  filters: {
    "FeeRebateAccumulated(uint128,uint248,uint248,uint248,uint64,uint64)"(
      accountId?: null,
      feeRebate?: null,
      volume30D?: null,
      feeRebateWithRate?: null,
      startBlockNumber?: null,
      endBlockNumber?: null
    ): FeeRebateAccumulatedEventFilter;
    FeeRebateAccumulated(
      accountId?: null,
      feeRebate?: null,
      volume30D?: null,
      feeRebateWithRate?: null,
      startBlockNumber?: null,
      endBlockNumber?: null
    ): FeeRebateAccumulatedEventFilter;

    "FeeReimbursed(uint128,uint248)"(
      accountId?: null,
      feeRebate?: null
    ): FeeReimbursedEventFilter;
    FeeReimbursed(accountId?: null, feeRebate?: null): FeeReimbursedEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;

    "VkHashesUpdated(bytes32[],uint16[])"(
      vkHashes?: null,
      sizes?: null
    ): VkHashesUpdatedEventFilter;
    VkHashesUpdated(vkHashes?: null, sizes?: null): VkHashesUpdatedEventFilter;
  };

  estimateGas: {
    accountIdAccumulatedFee(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    accountIdClaimPeriod(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    brevisBatchCallback(
      _chainId: BigNumberish,
      _proofDataArray: Brevis.ProofDataStruct[],
      _appCircuitOutputs: BytesLike[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    brevisCallback(
      _requestId: BytesLike,
      _appCircuitOutput: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    brevisProof(overrides?: CallOverrides): Promise<BigNumber>;

    claim(
      accountId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    claimer(overrides?: CallOverrides): Promise<BigNumber>;

    feeRebateTierModule(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    rewardToken(overrides?: CallOverrides): Promise<BigNumber>;

    rewardTokenDecimals(overrides?: CallOverrides): Promise<BigNumber>;

    setClaimer(
      _claimer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setFeeRebateTierModule(
      _feeRebateTierModule: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setRewardToken(
      _rewardToken: string,
      _decimals: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setVkHashes(
      _vkHashes: BytesLike[],
      _sizes: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    singleRun(
      _chainId: BigNumberish,
      _proofData: Brevis.ProofDataStruct,
      _merkleRoot: BytesLike,
      _merkleProof: BytesLike[],
      _nodeIndex: BigNumberish,
      _appCircuitOutput: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    validateRequest(
      _requestId: BytesLike,
      _chainId: BigNumberish,
      _extractInfos: Brevis.ExtractInfosStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    vkHashesToCircuitSize(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    accountIdAccumulatedFee(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    accountIdClaimPeriod(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    brevisBatchCallback(
      _chainId: BigNumberish,
      _proofDataArray: Brevis.ProofDataStruct[],
      _appCircuitOutputs: BytesLike[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    brevisCallback(
      _requestId: BytesLike,
      _appCircuitOutput: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    brevisProof(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    claim(
      accountId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    claimer(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    feeRebateTierModule(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    rewardToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    rewardTokenDecimals(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setClaimer(
      _claimer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setFeeRebateTierModule(
      _feeRebateTierModule: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setRewardToken(
      _rewardToken: string,
      _decimals: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setVkHashes(
      _vkHashes: BytesLike[],
      _sizes: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    singleRun(
      _chainId: BigNumberish,
      _proofData: Brevis.ProofDataStruct,
      _merkleRoot: BytesLike,
      _merkleProof: BytesLike[],
      _nodeIndex: BigNumberish,
      _appCircuitOutput: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    validateRequest(
      _requestId: BytesLike,
      _chainId: BigNumberish,
      _extractInfos: Brevis.ExtractInfosStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    vkHashesToCircuitSize(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
