/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface IFeeRebateTierModuleInterface extends utils.Interface {
  contractName: "IFeeRebateTierModule";
  functions: {
    "getFeeRebatePercentage(uint248)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getFeeRebatePercentage",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getFeeRebatePercentage",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IFeeRebateTierModule extends BaseContract {
  contractName: "IFeeRebateTierModule";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IFeeRebateTierModuleInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getFeeRebatePercentage(
      volume30D: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  getFeeRebatePercentage(
    volume30D: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    getFeeRebatePercentage(
      volume30D: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    getFeeRebatePercentage(
      volume30D: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getFeeRebatePercentage(
      volume30D: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
