/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export type SwapAmountStruct = {
  token0Amt: BigNumberish;
  token1Amt: BigNumberish;
};

export type SwapAmountStructOutput = [BigNumber, BigNumber] & {
  token0Amt: BigNumber;
  token1Amt: BigNumber;
};

export interface ISwapAmountInterface extends utils.Interface {
  contractName: "ISwapAmount";
  functions: {
    "getSwapAmount(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getSwapAmount",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "getSwapAmount",
    data: BytesLike
  ): Result;

  events: {};
}

export interface ISwapAmount extends BaseContract {
  contractName: "ISwapAmount";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ISwapAmountInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getSwapAmount(
      swapper: string,
      overrides?: CallOverrides
    ): Promise<[SwapAmountStructOutput] & { amount: SwapAmountStructOutput }>;
  };

  getSwapAmount(
    swapper: string,
    overrides?: CallOverrides
  ): Promise<SwapAmountStructOutput>;

  callStatic: {
    getSwapAmount(
      swapper: string,
      overrides?: CallOverrides
    ): Promise<SwapAmountStructOutput>;
  };

  filters: {};

  estimateGas: {
    getSwapAmount(
      swapper: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getSwapAmount(
      swapper: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
