/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../../../common";

export declare namespace Brevis {
  export type ProofDataStruct = {
    commitHash: BytesLike;
    vkHash: BytesLike;
    appCommitHash: BytesLike;
    appVkHash: BytesLike;
    smtRoot: BytesLike;
  };

  export type ProofDataStructOutput = [
    commitHash: string,
    vkHash: string,
    appCommitHash: string,
    appVkHash: string,
    smtRoot: string
  ] & {
    commitHash: string;
    vkHash: string;
    appCommitHash: string;
    appVkHash: string;
    smtRoot: string;
  };

  export type LogExtraInfoStruct = {
    valueFromTopic: BigNumberish;
    valueIndex: BigNumberish;
    contractAddress: AddressLike;
    logTopic0: BytesLike;
  };

  export type LogExtraInfoStructOutput = [
    valueFromTopic: bigint,
    valueIndex: bigint,
    contractAddress: string,
    logTopic0: string
  ] & {
    valueFromTopic: bigint;
    valueIndex: bigint;
    contractAddress: string;
    logTopic0: string;
  };

  export type LogInfoStruct = {
    logExtraInfo: Brevis.LogExtraInfoStruct;
    logIndex: BigNumberish;
    value: BytesLike;
  };

  export type LogInfoStructOutput = [
    logExtraInfo: Brevis.LogExtraInfoStructOutput,
    logIndex: bigint,
    value: string
  ] & {
    logExtraInfo: Brevis.LogExtraInfoStructOutput;
    logIndex: bigint;
    value: string;
  };

  export type ReceiptInfoStruct = {
    blkNum: BigNumberish;
    receiptIndex: BigNumberish;
    logs: [
      Brevis.LogInfoStruct,
      Brevis.LogInfoStruct,
      Brevis.LogInfoStruct,
      Brevis.LogInfoStruct,
      Brevis.LogInfoStruct
    ];
  };

  export type ReceiptInfoStructOutput = [
    blkNum: bigint,
    receiptIndex: bigint,
    logs: [
      Brevis.LogInfoStructOutput,
      Brevis.LogInfoStructOutput,
      Brevis.LogInfoStructOutput,
      Brevis.LogInfoStructOutput,
      Brevis.LogInfoStructOutput
    ]
  ] & {
    blkNum: bigint;
    receiptIndex: bigint;
    logs: [
      Brevis.LogInfoStructOutput,
      Brevis.LogInfoStructOutput,
      Brevis.LogInfoStructOutput,
      Brevis.LogInfoStructOutput,
      Brevis.LogInfoStructOutput
    ];
  };

  export type StorageInfoStruct = {
    blockHash: BytesLike;
    account: AddressLike;
    slot: BytesLike;
    slotValue: BytesLike;
    blockNumber: BigNumberish;
  };

  export type StorageInfoStructOutput = [
    blockHash: string,
    account: string,
    slot: string,
    slotValue: string,
    blockNumber: bigint
  ] & {
    blockHash: string;
    account: string;
    slot: string;
    slotValue: string;
    blockNumber: bigint;
  };

  export type TransactionInfoStruct = {
    leafHash: BytesLike;
    blockHash: BytesLike;
    blockNumber: BigNumberish;
    blockTime: BigNumberish;
    leafRlpPrefix: BytesLike;
  };

  export type TransactionInfoStructOutput = [
    leafHash: string,
    blockHash: string,
    blockNumber: bigint,
    blockTime: bigint,
    leafRlpPrefix: string
  ] & {
    leafHash: string;
    blockHash: string;
    blockNumber: bigint;
    blockTime: bigint;
    leafRlpPrefix: string;
  };

  export type ExtractInfosStruct = {
    smtRoot: BytesLike;
    receipts: Brevis.ReceiptInfoStruct[];
    stores: Brevis.StorageInfoStruct[];
    txs: Brevis.TransactionInfoStruct[];
  };

  export type ExtractInfosStructOutput = [
    smtRoot: string,
    receipts: Brevis.ReceiptInfoStructOutput[],
    stores: Brevis.StorageInfoStructOutput[],
    txs: Brevis.TransactionInfoStructOutput[]
  ] & {
    smtRoot: string;
    receipts: Brevis.ReceiptInfoStructOutput[];
    stores: Brevis.StorageInfoStructOutput[];
    txs: Brevis.TransactionInfoStructOutput[];
  };
}

export interface BrevisAppInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "brevisBatchCallback"
      | "brevisCallback"
      | "brevisProof"
      | "singleRun"
      | "validateRequest"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "brevisBatchCallback",
    values: [BigNumberish, Brevis.ProofDataStruct[], BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "brevisCallback",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "brevisProof",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "singleRun",
    values: [
      BigNumberish,
      Brevis.ProofDataStruct,
      BytesLike,
      BytesLike[],
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "validateRequest",
    values: [BytesLike, BigNumberish, Brevis.ExtractInfosStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "brevisBatchCallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "brevisCallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "brevisProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "singleRun", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "validateRequest",
    data: BytesLike
  ): Result;
}

export interface BrevisApp extends BaseContract {
  connect(runner?: ContractRunner | null): BrevisApp;
  waitForDeployment(): Promise<this>;

  interface: BrevisAppInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  brevisBatchCallback: TypedContractMethod<
    [
      _chainId: BigNumberish,
      _proofDataArray: Brevis.ProofDataStruct[],
      _appCircuitOutputs: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;

  brevisCallback: TypedContractMethod<
    [_requestId: BytesLike, _appCircuitOutput: BytesLike],
    [void],
    "nonpayable"
  >;

  brevisProof: TypedContractMethod<[], [string], "view">;

  singleRun: TypedContractMethod<
    [
      _chainId: BigNumberish,
      _proofData: Brevis.ProofDataStruct,
      _merkleRoot: BytesLike,
      _merkleProof: BytesLike[],
      _nodeIndex: BigNumberish,
      _appCircuitOutput: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  validateRequest: TypedContractMethod<
    [
      _requestId: BytesLike,
      _chainId: BigNumberish,
      _extractInfos: Brevis.ExtractInfosStruct
    ],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "brevisBatchCallback"
  ): TypedContractMethod<
    [
      _chainId: BigNumberish,
      _proofDataArray: Brevis.ProofDataStruct[],
      _appCircuitOutputs: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "brevisCallback"
  ): TypedContractMethod<
    [_requestId: BytesLike, _appCircuitOutput: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "brevisProof"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "singleRun"
  ): TypedContractMethod<
    [
      _chainId: BigNumberish,
      _proofData: Brevis.ProofDataStruct,
      _merkleRoot: BytesLike,
      _merkleProof: BytesLike[],
      _nodeIndex: BigNumberish,
      _appCircuitOutput: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "validateRequest"
  ): TypedContractMethod<
    [
      _requestId: BytesLike,
      _chainId: BigNumberish,
      _extractInfos: Brevis.ExtractInfosStruct
    ],
    [boolean],
    "view"
  >;

  filters: {};
}
