/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IFeeRebateTierModule,
  IFeeRebateTierModuleInterface,
} from "../IFeeRebateTierModule";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint248",
        name: "volume30D",
        type: "uint248",
      },
    ],
    name: "getFeeRebatePercentage",
    outputs: [
      {
        internalType: "uint64",
        name: "",
        type: "uint64",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IFeeRebateTierModule__factory {
  static readonly abi = _abi;
  static createInterface(): IFeeRebateTierModuleInterface {
    return new utils.Interface(_abi) as IFeeRebateTierModuleInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IFeeRebateTierModule {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IFeeRebateTierModule;
  }
}
