/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ISwapAmount, ISwapAmountInterface } from "../ISwapAmount";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "swapper",
        type: "address",
      },
    ],
    name: "getSwapAmount",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "token0Amt",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "token1Amt",
            type: "uint256",
          },
        ],
        internalType: "struct SwapAmount",
        name: "amount",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ISwapAmount__factory {
  static readonly abi = _abi;
  static createInterface(): ISwapAmountInterface {
    return new utils.Interface(_abi) as ISwapAmountInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISwapAmount {
    return new Contract(address, _abi, signerOrProvider) as ISwapAmount;
  }
}
