/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as apps from "./apps";
export type { apps };
import type * as interface from "./interface";
export type { interface };
import type * as lib from "./lib";
export type { lib };
