/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IFeeRebateTierModule,
  IFeeRebateTierModuleInterface,
} from "../../../contracts/FeeReimbursementApp.sol/IFeeRebateTierModule";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint248",
        name: "volume30D",
        type: "uint248",
      },
    ],
    name: "getFeeRebatePercentage",
    outputs: [
      {
        internalType: "uint64",
        name: "",
        type: "uint64",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IFeeRebateTierModule__factory {
  static readonly abi = _abi;
  static createInterface(): IFeeRebateTierModuleInterface {
    return new Interface(_abi) as IFeeRebateTierModuleInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IFeeRebateTierModule {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IFeeRebateTierModule;
  }
}
