/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IMigration,
  IMigrationInterface,
} from "../../../contracts/FeeReimbursementApp.sol/IMigration";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_account",
        type: "address",
      },
    ],
    name: "accountAccumulatedFee",
    outputs: [
      {
        internalType: "uint248",
        name: "",
        type: "uint248",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_account",
        type: "address",
      },
    ],
    name: "accountClaimPeriod",
    outputs: [
      {
        internalType: "uint64",
        name: "",
        type: "uint64",
      },
      {
        internalType: "uint64",
        name: "",
        type: "uint64",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IMigration__factory {
  static readonly abi = _abi;
  static createInterface(): IMigrationInterface {
    return new Interface(_abi) as IMigrationInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IMigration {
    return new Contract(address, _abi, runner) as unknown as IMigration;
  }
}
